== Install Alacritty

Creating a robust and visually appealing command portal requires tools that blend style, speed, and functionality. This section guides you through installing and configuring Alacritty with the Gruvbox-Material theme and Git Bash. Instructions are provided for both Windows and Mac.

Alacritty is a lightweight, GPU-accelerated terminal emulator known for its speed and simplicity. Follow the instructions for your platform:

=== Mac

Open your terminal (press `Cmd + Space`, type `Terminal`, and press `Enter`) and run the following incantation to install Alacritty via Homebrew:
[source,shell]
----
brew install alacritty
----

Verify the installation by launching Alacritty:

- Press `Cmd + Space`, type `alacritty`, and press `Enter`

If the terminal opens, the installation was successful. You might want to pin this to the desktop or the toolbar. You'll be using it a lot.

=== Windows

Open Git Bash by pressing `Win` key and typing `bash`. Then, summon Alacritty using the following command:
[source,shell]
----
winget install --id Alacritty.Alacritty -e
----

Verify the installation by launching Alacritty:

- Press `Win` key to open start menu and type `alacritty`, or
- Open the Run dialog (press `Win + R`), type `alacritty`, and press `Enter`.

If the terminal opens, the installation was successful. You might want to pin this to the desktop or the toolbar. You'll be using it a lot.

== Configure Alacritty

To ensure your Alacritty setup is fully optimized, copy the following configuration into your `alacritty.toml` file. This file is used to customize the appearance and behavior of Alacritty.

Open or create the Alacritty configuration file at:

- `%APPDATA%\alacritty\alacritty.toml` for Windows.
- `~/.config/alacritty/alacritty.toml` for Mac or Linux.

Use any simple text editor on the computer to replace the contents of the file with the following configuration:

[source,toml]
----
[general]
live_config_reload = true

[shell]
#program = "C:\Program Files\Git\bin\bash.exe"
#program = "/opt/homebrew/bin/bash"

[font]
size = 36

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[window.padding]
x = 8
y = 8

[colors.bright]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.normal]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.primary]
background = "0x282828"
foreground = "0xd4be98"

----

**Change bash shell**:

- For Windows uncomment the `program` line in the configuration containing `Program Files`.
- For Mac uncomment the `program` line in the configuration containing `homebrew`. Also confirm `bash` has been installed by running `brew install bash` from the terminal command line.

**Save the file and restart Alacritty to apply the configuration.** Once you have made these changes any change to this file will automatically update the terminal while it is running.

**Test your setup by launching Alacritty** and verifying that bash starts as the default shell.

---

Congratulations! You now have a sleek and powerful command portal, combining Alacritty's speed, the aesthetic brilliance of your custom configuration, and the versatility of your preferred shell.
