#!/usr/bin/env sh

podman run --rm \
	-v "$(pwd):/documents/" \
	asciidoctor/docker-asciidoctor \
	asciidoctor-epub3 \
	-D "build" \
	-a pdf-themesdir="./book/themes" \
	-a pdf-theme="dark-theme.yml" \
	-a pdf-fontsdir="./book/fonts" \
	"./book/index.adoc"