#!/usr/bin/env sh

# Docker image: https://hub.docker.com/r/asciidoctor/docker-asciidoctor
# Docker image repository: https://github.com/asciidoctor/docker-asciidoctor

podman run --rm \
	-v "$(pwd):/documents/" \
	asciidoctor/docker-asciidoctor \
	asciidoctor-pdf \
	-D "build" \
	-a pdf-themesdir="./book/themes" \
	-a pdf-theme="dark-theme.yml" \
	-a pdf-fontsdir="./book/fonts" \
	"./book/index.adoc"