== What's included in the book

This book is focused on learning to code in Go from the bash terminal command line, nothing more. There is nothing more authentic or rewarding than creating command-line tools from the command-line itself. Therefore, only those minimal skills required to use the command-line to open, edit, and run Go code from the terminal are covered.

=== The Code-Mage (cm) command

We have created a command-line setup tool and learning assistant written in Go to accompany this book: Code-Mage (abbreviated as `cm`). With one `cm init` command everything you need is installed and configured. Eventually, you can come back and examine everything Code-Mage did to better understand and customize it. (In fact, there's an entire book dedicated to it and advanced terminal mastery.)

Getting setup quickly is only the beginning of what the Code-Mage command can do:

- Dynamically display contextual help while you are typing
- Validate your work and catch bugs as you progress
- Create unit tests if you'd rather not type them in every time
- Time how long it takes you to complete a challenge
- Run a web-server for certain projects that require it
- Display community news and announcements
- Read this book to your web browser without Internet

The source code for Code-Mage is entirely public domain and open for review so you can compile and install your own if you feel uncomfortable—as you should—trusting a downloadable executable from the Internet. More on that later (see Preparation).

