== Why Go as a first language?

If you have never coded, just know Go is the best first language to learn for those who want a balanced introduction to programming and computer science while also learning a very real and marketable modern language.

=== Go is the Goldilocks of first languages

It is strictly typed enough to teach the importance of data types but loose enough to keep the syntax simple yet powerful. Go is also easily the least verbose and most understandable of all the strictly typed, statically linked modern languages.

=== Go solves real problems

Go was invented at Google to solve enterprise-scale problems facing one of the largest tech companies on the planet by innovators Rob Pike and Ken Thomson. These pioneers also contributed to the invention of UNIX, Unicode (think emojis), and C (in which all modern computer operating systems are written). It’s no surprise, then, that Go is the most significant enterprise language of the "cloud native" revolution. Practically every application of this modern movement has been written in Go, including Kubernetes, OpenShift, Docker, Podman, Consul, Nomad, Helm, Vault, and Terraform. You may not know those applications now, but you use them every day indirectly through the largest businesses in the world that critically depend on them.

=== Hackers love Go

Want to dual-class as a hacker and Code Mage? Go’s got you covered. Go is the darling of cybersecurity professionals all over the world, for good or ill. In fact, it is so popular Rob Pike officially asked people to stop making malware with it. In 2021, the sharp increase in incidents of malware written in Go was documented by several news outlets and watchdog groups. Go’s 100% compatibility with C, cross-platform compilation, significant standard library, embedded filesystem, decompilation challenges, and static linking make it perfect for hackers as well as engineers who just want to build a solid multi-call monolith binary (like BusyBox). Just search for "hackers love Golang" to read more about it.

=== Go is great for terminal apps

Go’s sweet spot is for creating backend server APIs and terminal command-line tools, which is what this book is all about. After all, aren’t commands just spells we cast from the command line?


