:compat-mode:
[preface]
= Preface

== Who should read this book

This book is written for anyone wanting to learn computer science and programming for practical applications development, the stuff that matters. 

While we have fun with the whole fantasy magic theme, everything in this book is very real and might even get you a job someday. It is true that this book can be reliably used as a text book for absolute beginners with enough algebra to understand what a mathematical function is. 

However, this book is very clearly not *only* intended for educational institutions. In fact, I wrote it mostly with pro-active, contentious parents in mind who want to give their kids a head-start in tech that they simply cannot find in most traditional education systems, the same reason, in fact, that I started SKILSTAK Coding Arts in 2013 with my own retirement money. My hope is that some of these parents, teachers, and mages will found coding clubs and communities of their own dedicated to helping others master the art of code and computer science (and increase their chances of gainful employment and happiness in the process). Even if coding turns out to be something you don't love as a career, it sure beats other jobs to pay the bills while you figure out what your true calling really is, and coding skills *always* enable a mage to conjure their own creations for whatever purpose later.

== What's included in the book

This book is focused on learning—as fast as possible—to code in the Go programming language from the Linux terminal command line. There is nothing more authentic or rewarding than creating command line tools from the command line itself. Therefore, only those minimal skills required to use the command line to open, edit, and run Go code from the terminal are covered. 

The fastest way to get a Linux terminal up and running is to install Podman and run a preconfigured Linux container image with everything needed already installed and configured. In fact, many software development teams do exactly this to ensure everyone is compiling against the same versions using the same testing and vetting tools. The very practice used in this book to setup a coding environment is itself a valuable, relevant skill (unlike many "for education" alternatives).

Hopefully, mages will continue to master other command line powers later and learn the dark arts of Linux distro selection and hardware installation (perhaps covered in additional "tomes" of magic from this author). 

== How to read this book 
