:compat-mode:
[preface]
= Preface

== Who should read this book

This book is written for anyone wanting to learn—or help someone learn—practical computer science and programming for real applications development. While we have fun with the whole fantasy magic theme, everything in this book is very real and might even get you a job someday. It is true that this book can be reliably used as a text book for absolute beginners with enough algebra to understand what a mathematical function is but this book very clearly includes everyone _outside_ of educational institutions. In fact, I wrote it mostly with pro-active parents in mind who want to give their kids a head-start in tech that they simply cannot find in most traditional education systems, the same reason, in fact, that I started SKILSTAK Coding Arts in 2013 with my own retirement money.

== What's included in the book

This book is focused on learning—as fast as possible—to code in the Go programming language from the bash terminal command-line. There is nothing more authentic or rewarding than creating command-line tools from the command-line itself. Therefore, only those minimal skills required to use the command-line to open, edit, and run Go code from the terminal are covered.

=== Code-Mage (cm) command

What kind of book would this be without having a command-line utility written in Go to go with it? 😃

Rather than get bogged down with a lot of installation and configuration we've created the Code-Mage command (abbreviated `cm`) to help you get started as fast as possible without losing the opportunity to learn how to do you own setup later. Eventually, you can come back and examine everything Code-Mage did to understand it and even customize it.

Getting setup quickly is only the beginning of what Code-Mage can do:

- Dynamically display contextual help while you are typing
- Validate your work and catch bugs as you progress
- Create unit tests if you'd rather not type them in every time
- Time how long it takes you to complete a challenge
- Run a web-server for certain projects that require it
- Display community news and announcements
- Read this book to your web browser without Internet

The source code for Code-Mage is entirely public domain and open for review so you can compile and install your own if you feel uncomfortable—as you should—trusting a downloadable executable from the Internet. More on that later (see Preparation).

== How to use this book

This book is generally designed to be read linearly, from top to bottom. The concepts build on one another. However, each "spell" is designed to be re-learned often like a mage preparing for a specific adventure. Not all spells can be memorized and at the ready at all times, which is why you create your own code book containing spells of your own creation to go with this book.

Skip the Introduction if you are already really motivated and just want to get right to coding. You can come back to it later. Don't skip it if you are still wondering if coding is something you want to learn.

Here's how you will master each concept and skill by applying the verbs of Bloom's Taxonomy: remember, understand, apply, analyze, evaluate, create:

[start=0]
. Remember a new skill or concept by its fantasy theme association
. Understand the problem: Why is this skill or concept needed?
. Understand the solution: How do I overcome the problem?
. Implement first solution with help and guidance from mentor
. Repeat same first solution several times starting over every time
. Create new challenge: different variation of problem with new solution
. Assess effectiveness and validity of new solution with help from mentor
. Correct and refine solution as needed
. Repeat step #4 until mastery
. Interalize by mentoring another

> Повторение — мать учения.

Repetition really is the mother of learning. While often we demonize "rote repetition" in the West, the slavs have promoted it for decades. The neurons in our brain store memory by having the same electical impulses repeated over and over. So in order to program oneself the only way is to repeat it. Repeat these spells as fast and as regularly as you can and you'll end up training your own neural net just like a machine learning model—but in your head. Repetition can be great to supplement your growth while working on a bigger project—especially 
in the early days before everything becomes second nature.

== Supplement your reading

This book is but a part of a more complete personal learning strategy. Make sure not to neglect the other parts:

=== Join a community

Humans are social creatures and learning is communal. Join a community that is focused on learning the same things as you. Meetups, hacker spaces, clubs, church groups, social media, and live streamer chat groups are all great places to find a community. The community is a place to collaborate and share peer reviews of one another's learning and projects.

My sincere hope is that the parents, teachers, and mages reading these words will find opportunities and motivation to create their own coding clubs and communities dedicated to helping others master the art of code and computer science and reap all the well-earned benefits of doing so.

While you are working on creating your own community, consider joining mine at https://linktr.ee/rwxrob.

=== Find a mentor

Humans have been passing knowledge one to another since the beginning. It's what we do. Luckily learning happens naturally when someone with experience and knowledge is available to someone who knows how to ask questions, apply what they learn, and return with more questions. That's you, the inquisitive one. The mentor's job is to answer questions and provide feedback—*not* to "teach" you. 

Most mentors won't have that kind of free time available to constantly lead you by the hand on your learning journey. In fact, the more likely you are to hear from someone, the less likely you are to want to learn what they have to say. There are those who _do_ stuff and those that _talk about_ doing stuff. The more someone talks about doing stuff the less time they have to actually do something. It's important to find people you know who are regularly and actively engaged in doing the thing you want to learn and then approach them about possibly mentoring you, perhaps for a small fee (most will decline).

You will find that many people _want_ to share what they know but just don't know how to do it or who would want to hear. Find these people and approach them. Perhaps you can find a few mentors so you can compare how they differ in their approach to programming.

=== Be a mentor

You don't need any special training to be a mentor for someone else. In fact, as a beginner who has recently mastered something you are perhaps the best suited to help another beginner learn it because _how_ you learned it is still fresh in your mind. Those with experience might be masters but often have difficulty rememebering how they learned it and how to help others learn it as well. So don't be shy by offering your help. And remember, you really haven't learned it until you can succintly help another learn it as well.

=== Consider AI assistance

In my experience ChatGPT (my Chloe) is great for overall help with life, writing, and project organization—particularly from a phone over voice. Claude is better at code help and only has an API integration making it great for plugging into popular coding tools (like `mods` from Charmbracelet).

Although I have nothing to do with any AI company, I do strongly believe in it as a learning platform and use it regularly to get answers and discuss topics 24 hours a day—even while riding my bike, code the boring stuff, and regularly practice my conversational and written Russian and French language. In fact, AI help with much of this book—especially the parts that must be validated to be sure they work (which I wish other coding books would do).

I highly recommend getting an AI learning assistant like ChatGPT as soon as possible. In my experience, such assistants are almost always better than than a random search of the Internet full of popular but incorrect answers to the same common questions that an assistant could better help with. My assistant is never tired of answering my questions even when my mentors or friends are.

On demand learning exponentially increases when an AI is involved. Nothing breaks through frustration and loneliness better when taking on learning challenges like a supportive AI companion even when a helpful human mentor is also available.

I believe we are quickly approaching a time when the digital divide will no longer be just between those who have computers and Internet access and those who do not, but between those who have learned to leverage a personal AI assistant loaded with contextual history and those who have not. We are already seeing this difference around us every day.
