= Prepare to code

> Learning happens in the lab, not the lecture hall.

You are probably excited to get going and we've done our best to help you get started as quickly as possible. Here's a summary of what you'll need to do to prepare:

[start=0]
. Get a computer
. Learn to type from home row
. Connect with a supportive learning community
. Install the Go compiler and Code-Mage using Go
. Install the development tools you'll need (with help from Code-Mage)
. Learn to learn, take notes, and use your new development tools

For most people this preparation takes a few hours, but there is simply no avoiding it if you want to actually learn and have that learning stick with you later.

[CAUTION]
====
Now is the point where it is really easy to get distracted. You could learn everything there is to know about bash, Linux, vim, tmux, and more. You could spent endless hours going online to find the absolute best possible terminal, colors and configuration. You could fight endlessly with people about the best editor, Linux distribution, first programming language, or color scheme. You could defend your decision to use your preferred operating system.

Just don't do it!

You can waste that time later. For now, you have a lot to get ready and learn before coding, then, after you have got some real coding skill you will be better prepared to revisit these things and your arguments with random trolls (who haven't coded yet) will carry more weight because you have actually _done_ something.
====

include::prep/start-taking-notes.adoc[]

include::prep/computer.adoc[]

include::prep/get-email-account.adoc[]

include::prep/create-slack-account.adoc[]

include::prep/create-github-account.adoc[]

include::prep/learn-basic-markdown.adoc[]

include::prep/getgo.adoc[]

include::prep/installcm.adoc[]

include::prep/cminit.adoc[]

include::prep/start-alacritty.adoc[]

include::prep/learnshell.adoc[]

include::prep/learnvim.adoc[]

include::prep/learntmux.adoc[]

include::prep/learnw3m.adoc[]

include::prep/learn-mods-ai.adoc[]

